### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by davidfurlong** [standard-crypto/farcaster-js#435]
Hey just wanted to say a big thank you for this library - it's helped me tremendously cut down the amount of code I need to write and the types are also super useful. 

I've run into two little things while using this library, and thought it would make sense to leave them here in case they're useful. 
1. The `fetchUserCastLikes` function has an unusual type and comment that might be a mistake: https://github.com/standard-crypto/farcaster-js/blob/develop/docs/classes/index.MerkleAPIClient.md#fetchusercastlikes "Fetch the latest cast for the user, if there is one". The return type is a `Cast` although `GET /v2/user-cast-likes` returns a form of `Like` object with different properties. 
2. The errors by the library when a request fails don't seem to include the farcaster API request error message. The farcaster api response body usually includes a JSON body `{ errors: Array<{ message: string }>` when it errors, and it would be super useful to have an easy way to get this. There may already be a way that I'm missing - I saw that I can get this error via the logger, but not via the rejected promise.

Anyways I really appreciate the work on this library 🙏

Feel free to close this issue, and I hope I haven't done too big a faux pas by ignoring the issue template

**Comment by gsgalloway** [comment]
Thanks for flagging @davidfurlong! You're right about the incorrect type on `fetchUserCastLikes`, which should be fixed now.

I've added a new method plus example code for parsing API error strings from any `error` thrown by the client: [example here](https://github.com/standard-crypto/farcaster-js/tree/0427f181817c946c935ee52d9be671cbf3401b00#parse-an-api-error-response)

**Comment by davidfurlong** [comment]
Awesome that was fast!
