### ISSUE TITLE
Add the ability to pass an authentication token instead of a wallet to the MerkleApiClient constructor

### ISSUE THREAD

**Issue by davidfurlong** [standard-crypto/farcaster-js#438]
**Is your feature request related to a problem? Please describe.**

If I want to authenticate a request on behalf of a user who has generated an authentication token and given it to my app via a signature, I can't currently do it. Some endpoints in fact require this user's authentication token rather than someone else's, like `publishCast`. 

**Describe the solution you'd like**

Add the ability to pass an authentication token instead of a wallet to the MerkleApiClient constructor. 
https://farcasterxyz.notion.site/Merkle-v2-API-Documentation-c19a9494383a4ce0bd28db6d44d99ea8#c8290028e8f64238bdd2db8938b29b9b

**Describe alternatives you've considered**

Using fetch directly instead of this sdk

**Additional context**

none

**Comment by gsgalloway** [comment]
@davidfurlong LMK what you think:
- [new constructor](https://github.com/standard-crypto/farcaster-js/pull/439/files#diff-515f55d91ec94751e012423038e59df01278a08bb835c1fc77a0f19dd13d58f8R67)
- [example](https://github.com/standard-crypto/farcaster-js/pull/439/files?short_path=0b5ca11#diff-0b5ca119d2be595aa307d34512d9679e49186307ef94201e4b3dfa079aa89938)

**Comment by davidfurlong** [comment]
Yeah that's awesome, thanks!
