### ISSUE TITLE
Timestamp for posts returns a date far in the future

### ISSUE THREAD

**Issue by alexreyes** [standard-crypto/farcaster-js#526]
**Describe the bug**
After getting casts with `fetchCastsForUser`, whenever I print out the timestamp I get a unix timestamp that's far, far far ahead in the future. 

Example value: 1678166638000 which is Sat, 25 Dec **_55148_**

**To Reproduce**
1. Get post with fetchCastsForUser()
2. Print timestamp value

**Expected behavior**
A real timestamp

**Desktop (please complete the following information):**
 - OS: macOS 13.2
 - Node version: v16.19.1
 - Code Version: 5.5.3

**Comment by gsgalloway** [comment]
Thanks for reaching out!

It looks like the Warpcast API returns timestamps as epoch milliseconds, not epoch seconds. See Warpcast sample API response here: https://warpcast.notion.site/Warpcast-v2-API-Documentation-c19a9494383a4ce0bd28db6d44d99ea8#adaad686f0ad4e29b1bd455e24b55b6e

If you need epoch seconds you should be able to just divide each timestamp by 1000

**Comment by alexreyes** [comment]
Ahhh, okay my bad! Thanks @gsgalloway
