### ISSUE TITLE
Add Wrapcast API methods for signer requests

### ISSUE THREAD

**Issue by michaelhly** [standard-crypto/farcaster-js#539]
**Is your feature request related to a problem? Please describe.**
Add wrapper methods for new Warpcast APIs supporting the signer request flow:
https://warpcast.notion.site/Warpcast-v2-API-Documentation-c19a9494383a4ce0bd28db6d44d99ea8#13cb11cba1114002adc928c5fa679364

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
https://warpcast.notion.site/Warpcast-API-Docs-Signer-Requests-Public-e02ef71883374d2ca8d27239a8cc35d5

**Comment by gsgalloway** [comment]
On it
