### ISSUE TITLE
Support hub APIs

### ISSUE THREAD

**Issue by michaelhly** [standard-crypto/farcaster-js#540]
**Is your feature request related to a problem? Please describe.**
This library generated a client off of outdated openapi [specs](https://github.com/standard-crypto/farcaster-js/blob/develop/src/merkleAPI/swagger/spec.json) and requires manual modification over generated code for ongoing maintenance, which is not ideal.

Farcaster [hubs](https://github.com/farcasterxyz/hubble) are launching soon, but we still need to rely on the Warpcast API to retrieve data such as a user's follower graph from Wrapcast.

We should redirect some of the API helpers in this library to point to farcaster hubs instead of Warpcast APIs.

**Describe the solution you'd like**
- Generate Typescript bindings off of farcaster's [protobuf specs](https://github.com/farcasterxyz/hubble/tree/main/packages/protobufs#farcasterprotobufs)
- Combine grpc client with MerkleAPI client to support necessary Warpcast API methods
- Mark duplicate Warpcast API methods as legacy (or just remove them)
- Remove everything generated from the outdated openapi specifications

**Describe alternatives you've considered**
Simply re-export farcaster packages in [index.ts](https://github.com/standard-crypto/farcaster-js/blob/develop/src/index.ts)
```ts
export * from '@farcaster/protobufs';
export * from '@farcaster/utils';
```
But we'll have to deal with the hub client and the Merkle client which is bad developer ergonomics.

**Additional context**

**Comment by gsgalloway** [comment]
Agreed, thanks. Will incorporate this soon

**Comment by gsgalloway** [comment]
This went out in v7.0 release
