### ISSUE TITLE
Add ability to use 'embeds' and 'mentions' when publishing casts

### ISSUE THREAD

**Issue by seeARMS** [standard-crypto/farcaster-js#621]
**Is your feature request related to a problem? Please describe.**
Warpcast no longer processes text to generate embeds: https://warpcast.com/gt/0xfca6bf

We run a bot that posts content from our users. Historically, Warpcast crawled links contained within our casts, then used that as the cast image, which was great. Now, according to the above, the Warpcast team does not parse text anymore, so we manually need to add images/links to the `embeds` array when publishing a cast.

This package does not support adding in fields beyond text when publishing a cast.

**Describe the solution you'd like**
- modify `publishCast` to support adding in the embeds/mentions array; or,
- create a new method to add more complex publishing options like embeds/mentions, and leave `publishCast` to be a simple text cast

**Describe alternatives you've considered**
We can use hubs directly, eg https://github.com/farcasterxyz/hub-monorepo/blob/main/packages/hub-nodejs/examples/make-cast/index.ts, but we already rely on this package so would prefer not to migrate.

**Additional context**
Weeks ago, when Warpcast crawled links (beautiful):

<img width="623" alt="image" src="https://github.com/standard-crypto/farcaster-js/assets/3957773/cde26e23-2872-4f34-9dd6-9885bb5c8f91">

Now (ugly):

<img width="606" alt="image" src="https://github.com/standard-crypto/farcaster-js/assets/3957773/bc7c9789-3d95-4ca2-b324-7ab2c0a5f8ab">

**Comment by gsgalloway** [comment]
Thanks @seeARMS, we'll get this addressed shortly

**Comment by seeARMS** [comment]
Hi @gsgalloway, any updates here?

Appreciate the help!

**Comment by gsgalloway** [comment]
Hi @seeARMS 

We've been discussing with the Warpcast team the future of this package, in light of the Warpcast team's plan to deprecate their API. We were unsure as to whether we should in turn be deprecating this package and redirecting users to the hub APIs. Apologies that we haven't been communicative here along the way.

Latest understanding is that the Neynar team will be replicating the Warpcast API sometime in the upcoming couple of months, and that it should be a drop-in replacement.

We should be able to support this feature, then, and include it in the migration to Neynar's replacement.

**Comment by gsgalloway** [comment]
Supported in new Neynar API package

**Comment by seeARMS** [comment]
Thanks.

Is the new package published to npm?

```
➜ yarn add @standard-crypto/farcaster-js-neynar
➤ YN0027: @standard-crypto/farcaster-js-neynar@unknown can't be resolved to a satisfying range
➤ YN0035: The remote server failed to provide the requested resource
➤ YN0035:   Response Code: 404 (Not Found)
➤ YN0035:   Request Method: GET
➤ YN0035:   Request URL: https://registry.yarnpkg.com/@standard-crypto%2ffarcaster-js-neynar

```

**Comment by gsgalloway** [comment]
Not yet, need another day or two to wrap up final steps

**Comment by gsgalloway** [comment]
Available now @seeARMS
