### ISSUE TITLE
Support arbitrary strings for cast targets

### ISSUE THREAD

**Issue by gsgalloway** [standard-crypto/farcaster-js#656]
As per [FIP-2](https://github.com/farcasterxyz/protocol/discussions/71#discussion-5056199), we need to support arbitrary cast targets. Currently the library enforces that cast targets match a regex for cast hashes only.

Example: chain://eip155:base/erc721:0x9a9AcbA3c0799018C85A71DcD8A5C916468C9618

**Comment by gsgalloway** [comment]
The Warpcast API is returning 400 errors when attempting to use a string as a cast's reply target:
https://github.com/standard-crypto/farcaster-js/actions/runs/6424016099/job/17443751501

Since the Warpcast API is deprecated, it makes sense to push through the migration of this library to the Hub REST API and the Neynar API rather than reverse engineer what the Warpcast client is doing for non-cast reply targets.

**Comment by Sam-Scolari** [comment]
That makes sense, wasn't aware the Warpcast API was being deprecated when I made the pull request. I'll be switching to hub apis for now

**Comment by gsgalloway** [comment]
Hub APIs now supported in release 6.0
