### ISSUE TITLE
Unable to submitCast into channel / missing parentUrl

### ISSUE THREAD

**Issue by hellno** [standard-crypto/farcaster-js#749]
**Describe the bug**
```
 const writeClient = new HubRestAPIClient({ hubUrl });
 const publishCastResponse = await writeClient.submitCast(data, fid, signerPrivateKey)
```

cannot send parentUrl in data, so cannot submit casts into channels

**Comment by hellno** [comment]
@piratekev @gsgalloway can you help with this? I'm up for contributing a PR but not sure which steps are required.

**Comment by piratekev** [comment]
@hellno I published new versions of farcaster-js and farcaster-js-hub-rest that support this now. 

Checkout [this](https://github.com/standard-crypto/farcaster-js/blob/develop/packages/farcaster-js-hub-rest/tests/integration/hubRestAPIClient.ts#L99) test: 
```
const responseMessage = await client.submitCast({
    text: 'This is a test cast submitted from farcaster-js-hub-rest into a channel',
    parentUrl: 'https://warpcast.com/~/channel/test'
}, userGaviBotFid, signerPrivateKey);

```

**Comment by hellno** [comment]
so cool, thank you for this 🔥
