### ISSUE TITLE
Signers link is broken

### ISSUE THREAD

**Issue by avaer** [standard-crypto/farcaster-js#752]
The Farcaster link here leads to 404:

https://github.com/standard-crypto/farcaster-js?tab=readme-ov-file#signers
https://docs.farcaster.xyz/protocol/concepts#signers
![image](https://github.com/standard-crypto/farcaster-js/assets/6926057/600bde8f-5848-47de-aa82-1ed419366707)

**Comment by piratekev** [comment]
Thanks for the heads up @avaer
